# roles/aws-iam-group-create/tasks/main.yml

---
- name: aws-iam-group-create - create iam group
  iam_group:
    name: '{{ iam_group_name }}'
    state: present
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
  tags:
    - aws-iam-group-create