# roles/linux-install-docker/tasks/debian.yml

---
- name: linux-install-docker - debian - install required packages
  apt:
    name:
      - curl
      - gnupg-agent
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    force_apt_get: yes
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-docker


- name: linux-install-docker - debian - add official repository GPG key
  apt_key:
    url: '{{ docker_repository_gpg_key_debian }}'
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-docker


- name: linux-install-docker - debian - add apt repository
  apt_repository:
    repo: '{{ docker_apt_repository_debian }}'
    filename: 'docker'
    state: present
    update_cache: no
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-docker


- name: linux-install-docker - debian - install docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-docker