# roles/aws-ec2-eip-associate/taska/main.yml

---
- name: aws-ec2-eip-associate - associate eip for ec2 instance
  ec2_eip:
    device_id: '{{ ec2instance.instances[0].id }}'
    ip: '{{ ec2eip.public_ip }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
    state: present
  register: ec2eip
  tags:
    - aws-ec2-eip-associate


- name: aws-ec2-eip-associate - display ec2 eip information
  debug: var=ec2eip
  tags:
    - aws-ec2-eip-associate