# linux-install-zabbix-agent/tasks/ubuntu.yml

---
- name: ubuntu - install libcurl3 for trusty and xenial
  apt:
    name: libcurl3
    state: present
  when: ansible_distribution_major_version == '14' or ansible_distribution_major_version == '16'
  tags:
    - linux-install-zabbix-agent


- name: ubuntu - install libcurl4 for bionic and focal
  apt:
    name: libcurl4
    state: present
  when: ansible_distribution_major_version == '18' or ansible_distribution_major_version == '20'
  tags:
    - linux-install-zabbix-agent


- name: ubuntu - install repository
  apt:
    deb: '{{ zabbix_repo_ubuntu }}'
  tags:
    - linux-install-zabbix-agent


- name: ubuntu - install zabbix-agent
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  tags:
    - linux-install-zabbix-agent