# roles/aws-ec2-start/taska/main.yml

---
- name: aws-ec2-start - search ec2 instance
  ec2_remote_facts:
    filters:
      'tag:{{ tag_key }}': '{{ tag_value }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
  register: ec2instance
  tags:
    - aws-ec2-start


- name: aws-ec2-start - start ec2 instance
  ec2:
    instance_ids: '{{ ec2instance.instances[0].id }}'
    region: '{{ ec2instance.instances[0].region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    state: running
    wait: True
  tags:
    - aws-ec2-start