# linux-install-nginx/tasks/debian.yml

---
- name: linux-install-nginx - debian - install required packages
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
    force_apt_get: yes
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-nginx


- name: linux-install-nginx - debian - add official repository GPG key
  apt_key:
    id: '{{ nginx_repository_gpg_fingerprint }}'
    url: '{{ nginx_repository_gpg_key }}'
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-nginx


- name: linux-install-nginx - debian - add apt repository
  apt_repository:
    repo: '{{ nginx_apt_repository_debian }}'
    filename: 'nginx'
    state: present
    update_cache: no
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-nginx


- name: linux-install-nginx - debian - install nginx
  apt:
    name: 
      - nginx
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Debian'
  tags:
    - linux-install-nginx