# linux-install-nginx/tasks/main.yml

---
- name: linux-install-nginx - gather facts
  setup:
    gather_subset:
      - '!all'
  tags:
    - linux-install-nginx


- name: linux-install-nginx - including tasks for OS
  include_tasks: '{{ ansible_distribution|lower }}.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  notify: 'linux-install-nginx - restarted and enabled nginx'
  tags:
    - linux-install-nginx