# roles/aws-ec2-eip-delete/taska/main.yml

---
- name: aws-ec2-eip-delete - delete elastic ip
  ec2_eip:
    ip: '{{ ec2eip.public_ip }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
    state: absent
  register: ec2eip
  tags:
    - aws-ec2-eip-delete


- name: aws-ec2-eip-delete - display eip information
  debug:
    var: ec2eip
  tags:
    - aws-ec2-eip-delete